### ISSUE TITLE
Ausencia de integrantes

### ISSUE THREAD

**Issue by cosmoscalibur** [JonathanQuiroz/Proyecto-Zeus#3]
Se observa la ausencia de un integrante a pesar de ser el propietario del repositorio.  
¿Serán 4 o 5 participantes?

**Comment by JonathanQuiroz** [comment]
5 profe, solo que lo ultimo que vamos a hacer es el readme por tal motivo
no me he agregado

**Comment by cosmoscalibur** [comment]
La lista de contribuidores del repositorio (no el `README.md`) muestra 4. ¿Que ha sucedido con la adición de Eduin que es el único estudiante que falta en los repositorios?

**Comment by cosmoscalibur** [comment]
Referencia al reporte [1 del nuevo repositorio](https://github.com/EduinHSERNA/Taller-Algebra-Computacional-Alternativo/issues/1). Recordar que participación no es estar enunciados sino la base al registro de `commit`s. con aportes funcionales.
